### ISSUE TITLE
Use AST library to parse the Python source code

### ISSUE THREAD

**Issue by shuttle1987** [utting98/py-to-cpp-converter#1]
At the moment you have been doing a lot of text based manipulations to parse the Python source. Instead of reinventing that wheel completely you may wish to make use of the AST library that comes with Python that will parse the python source into an Abstract Syntax Tree: https://docs.python.org/3/library/ast.html

**Comment by utting98** [comment]
Investigated this suggestion and it seems the most sensible approach, currently working on a method on a new file parsing system to return relevant line tokens this way and make substitutions based on these. Will upload this improved method to the repo when got a bit more up to date, thanks for the suggestion.
